#!/bin/bash
#
# [QuickBox ARM64 motd]
#
# GitHub:   https://github.com/amefs/quickbox-arm64
# Author:   Amefs
# Current version:  v1.0.0
# URL:
# Original Repo:    https://github.com/QuickBox/QB
# Credits to:       QuickBox.io
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
#################################################################################
QUICKBOX_VERSION=v1.1.2
PUBLICIP=$(ip addr show | grep 'inet ' | grep -v 127.0.0.1 | awk '{print $2}' | cut -d/ -f1 | head -n 1)
printf "Welcome to QuickBox ARM64 %s" "${QUICKBOX_VERSION}"
printf "\n"
if [[ -f /install/domain.info ]]; then
	printf " * Dashboard:      https://%s\n"  "$(cat /install/domain.info)"
else
	printf " * Dashboard:      https://%s\n" "${PUBLICIP}"
fi
printf " * Documentation:  https://www.ptbox.dev\n"
printf " * Support:        https://github.com/amefs/quickbox-arm64/issues\n"
printf "\n"
[ -x /usr/bin/screenfetch ] && /usr/bin/screenfetch -a /etc/QuickBox/packages/system/auxiliary/quickbox-logo
printf "\n"